// Defines the UEFI Simple Text Input Protocol

#ifndef __EFI_SIMPLE_TEXT_INPUT_PROTOCOL__
#define __EFI_SIMPLE_TEXT_INPUT_PROTOCOL__

typedef struct _EFI_SIMPLE_TEXT_INPUT_PROTOCOL EFI_SIMPLE_TEXT_INPUT_PROTOCOL;
#define EFI_SIMPLE_TEXT_INPUT_PROTOCOL_GUID {0x387477c1,0x69c7,0x11d2,{0x8e,0x39,0x00,0xa0,0xc9,0x69,0x72,0x3b}}

// DEPENDENCIES

#ifndef __EFI_DATA_TYPES__
#include "../../System/DataTypes.h"
#endif //__EFI_DATA_TYPES__

// RELATED DEFINITIONS

#define EFI_SCAN_CODE_NULL 0x00
#define EFI_SCAN_CODE_UP_ARROW 0x01
#define EFI_SCAN_CODE_DOWN_ARROW 0x02
#define EFI_SCAN_CODE_RIGHT_ARROW 0x03
#define EFI_SCAN_CODE_LEFT_ARROW 0x04
#define EFI_SCAN_CODE_HOME 0x05
#define EFI_SCAN_CODE_END 0x06
#define EFI_SCAN_CODE_INSERT 0x07
#define EFI_SCAN_CODE_DELETE 0x08
#define EFI_SCAN_CODE_PAGE_UP 0x09
#define EFI_SCAN_CODE_PAGE_DOWN 0x0a
#define EFI_SCAN_CODE_FUNCTION_1 0x0b
#define EFI_SCAN_CODE_FUNCTION_2 0x0c
#define EFI_SCAN_CODE_FUNCTION_3 0x0d
#define EFI_SCAN_CODE_FUNCTION_4 0x0e
#define EFI_SCAN_CODE_FUNCTION_5 0x0f
#define EFI_SCAN_CODE_FUNCTION_6 0x10
#define EFI_SCAN_CODE_FUNCTION_7 0x11
#define EFI_SCAN_CODE_FUNCTION_8 0x12
#define EFI_SCAN_CODE_FUNCTION_9 0x13
#define EFI_SCAN_CODE_FUNCTION_10 0x14
#define EFI_SCAN_CODE_FUNCTION_11 0x15
#define EFI_SCAN_CODE_FUNCTION_12 0x16
#define EFI_SCAN_CODE_FUNCTION_13 0x68
#define EFI_SCAN_CODE_FUNCTION_14 0x69
#define EFI_SCAN_CODE_FUNCTION_15 0x6A
#define EFI_SCAN_CODE_FUNCTION_16 0x6B
#define EFI_SCAN_CODE_FUNCTION_17 0x6C
#define EFI_SCAN_CODE_FUNCTION_18 0x6D
#define EFI_SCAN_CODE_FUNCTION_19 0x6E
#define EFI_SCAN_CODE_FUNCTION_20 0x6F
#define EFI_SCAN_CODE_FUNCTION_21 0x70
#define EFI_SCAN_CODE_FUNCTION_22 0x71
#define EFI_SCAN_CODE_FUNCTION_23 0x72
#define EFI_SCAN_CODE_FUNCTION_24 0x73
#define EFI_SCAN_CODE_ESCAPE 0x17
#define EFI_SCAN_CODE_PAUSE 0x48
#define EFI_SCAN_CODE_MUTE 0x7F
#define EFI_SCAN_CODE_VOLUME_UP 0x80
#define EFI_SCAN_CODE_VOLUME_DOWN 0x81
#define EFI_SCAN_CODE_BRIGHTNESS_UP 0x100
#define EFI_SCAN_CODE_BRIGHTNESS_DOWN 0x101
#define EFI_SCAN_CODE_SUSPEND 0x102
#define EFI_SCAN_CODE_HIBERNATE 0x103
#define EFI_SCAN_CODE_TOGGLE_DISPLAY 0x104
#define EFI_SCAN_CODE_RECOVERY 0x105
#define EFI_SCAN_CODE_EJECT 0x106
#define EFI_SCAN_CODE_OEM_RESERVED 0xFFFF

typedef struct {
    UINT16 ScanCode;
    CHAR16 UnicodeChar;
} EFI_INPUT_KEY;

// PROTOTYPES

typedef EFI_STATUS (EFIAPI *EFI_INPUT_RESET) (
    IN EFI_SIMPLE_TEXT_INPUT_PROTOCOL *This,
    IN BOOLEAN ExtendedVerification
);

typedef EFI_STATUS (EFIAPI *EFI_INPUT_READ_KEY) (
    IN EFI_SIMPLE_TEXT_INPUT_PROTOCOL *This,
    OUT EFI_INPUT_KEY *Key
);

struct _EFI_SIMPLE_TEXT_INPUT_PROTOCOL {
    EFI_INPUT_RESET Reset;
    EFI_INPUT_READ_KEY ReadKeyStroke;
    EFI_EVENT WaitForKey;
};
#endif //__EFI_SIMPLE_TEXT_INPUT_PROTOCOL__